//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyvat.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationTypeError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationTypeError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easyvat.Common.Resources.ValidationTypeError", typeof(ValidationTypeError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 419.
        /// </summary>
        public static string Cost4KamutKniaKupa {
            get {
                return ResourceManager.GetString("Cost4KamutKniaKupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 411.
        /// </summary>
        public static string CostYehidaKupa {
            get {
                return ResourceManager.GetString("CostYehidaKupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 413.
        /// </summary>
        public static string KamutParitKniaKupa {
            get {
                return ResourceManager.GetString("KamutParitKniaKupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        public static string NumHeshbonitMaam {
            get {
                return ResourceManager.GetString("NumHeshbonitMaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 402.
        /// </summary>
        public static string NumOsek {
            get {
                return ResourceManager.GetString("NumOsek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 407.
        /// </summary>
        public static string SchumHeshWithMaam {
            get {
                return ResourceManager.GetString("SchumHeshWithMaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501.
        /// </summary>
        public static string SoftwareIdNum {
            get {
                return ResourceManager.GetString("SoftwareIdNum", resourceCulture);
            }
        }
    }
}
