//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easyvat.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easyvat.Common.Resources.ValidationErrorMessage", typeof(ValidationErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מספר דרכון.
        /// </summary>
        public static string _397 {
            get {
                return ResourceManager.GetString("_397", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר דרכון לא תקין, מותרות ספרות ואותיות בלבד.
        /// </summary>
        public static string _398 {
            get {
                return ResourceManager.GetString("_398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מדינה.
        /// </summary>
        public static string _399 {
            get {
                return ResourceManager.GetString("_399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המדינה שהוזנה אינה מוכרת עבור שדה זה.
        /// </summary>
        public static string _400 {
            get {
                return ResourceManager.GetString("_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מספר עוסק מורשה של בית העסק.
        /// </summary>
        public static string _401 {
            get {
                return ResourceManager.GetString("_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר עוסק מורשה של בית העסק אינו תקין.
        /// </summary>
        public static string _402 {
            get {
                return ResourceManager.GetString("_402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מספר חשבונית מע&quot;מ.
        /// </summary>
        public static string _403 {
            get {
                return ResourceManager.GetString("_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר חשבונית מע&quot;מ לא תקין.
        /// </summary>
        public static string _404 {
            get {
                return ResourceManager.GetString("_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין סכום חשבונית כולל מע&quot;מ.
        /// </summary>
        public static string _406 {
            get {
                return ResourceManager.GetString("_406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סכום החשבונית כולל מע&quot;מ אינו תקין.
        /// </summary>
        public static string _407 {
            get {
                return ResourceManager.GetString("_407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין תאור מוצר.
        /// </summary>
        public static string _409 {
            get {
                return ResourceManager.GetString("_409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מחיר למוצר בודד.
        /// </summary>
        public static string _410 {
            get {
                return ResourceManager.GetString("_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר למוצר בודד אינו תקין.
        /// </summary>
        public static string _411 {
            get {
                return ResourceManager.GetString("_411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין כמות פריטים.
        /// </summary>
        public static string _412 {
            get {
                return ResourceManager.GetString("_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כמות פריטים לא תקינה.
        /// </summary>
        public static string _413 {
            get {
                return ResourceManager.GetString("_413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאור מוצר לא תקין.
        /// </summary>
        public static string _414 {
            get {
                return ResourceManager.GetString("_414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מספר בר-קוד.
        /// </summary>
        public static string _416 {
            get {
                return ResourceManager.GetString("_416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר בר-קוד לא תקין.
        /// </summary>
        public static string _417 {
            get {
                return ResourceManager.GetString("_417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סך מחיר המוצרים גדול או קטן מסכום החשבונית.
        /// </summary>
        public static string _418 {
            get {
                return ResourceManager.GetString("_418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סכום הפריטים שהוזנו לא תקין.
        /// </summary>
        public static string _419 {
            get {
                return ResourceManager.GetString("_419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין שם בית עסק.
        /// </summary>
        public static string _420 {
            get {
                return ResourceManager.GetString("_420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם בית עסק לא תקין.
        /// </summary>
        public static string _421 {
            get {
                return ResourceManager.GetString("_421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין כתובת בית עסק.
        /// </summary>
        public static string _422 {
            get {
                return ResourceManager.GetString("_422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת בית עסק לא תקינה.
        /// </summary>
        public static string _423 {
            get {
                return ResourceManager.GetString("_423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין עיר בית עסק.
        /// </summary>
        public static string _424 {
            get {
                return ResourceManager.GetString("_424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עיר בית העסק לא תקינה.
        /// </summary>
        public static string _425 {
            get {
                return ResourceManager.GetString("_425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין טלפון בית העסק.
        /// </summary>
        public static string _426 {
            get {
                return ResourceManager.GetString("_426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון בית העסק לא תקין.
        /// </summary>
        public static string _427 {
            get {
                return ResourceManager.GetString("_427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין שם קופאי.
        /// </summary>
        public static string _428 {
            get {
                return ResourceManager.GetString("_428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קופאי לא תקין.
        /// </summary>
        public static string _429 {
            get {
                return ResourceManager.GetString("_429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סך מחיר המוצרים גדול מסכום החשבונית.
        /// </summary>
        public static string _430 {
            get {
                return ResourceManager.GetString("_430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להוסיף פריטים לחשבונית. חשבונית ללא מוצרים אינה תקינה.
        /// </summary>
        public static string _432 {
            get {
                return ResourceManager.GetString("_432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין מספר עוסק מורשה של בית התוכנה..
        /// </summary>
        public static string _500 {
            get {
                return ResourceManager.GetString("_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר עוסק מורשה של בית התוכנה אינו תקין.
        /// </summary>
        public static string _501 {
            get {
                return ResourceManager.GetString("_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין את סכום המוצרים .
        /// </summary>
        public static string _503 {
            get {
                return ResourceManager.GetString("_503", resourceCulture);
            }
        }
    }
}
